# Checking model selection against CSDA/Length

In [37]:
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
CSDA = "/Volumes/easystore/proton-kaon/docs/selected_kaon_csda.csv"
MODEL = "/Volumes/easystore/proton-kaon/docs/selected_kaon_model.csv"
MASS = "/Volumes/easystore/proton-deuteron/csv/picky+match.csv"

In [39]:
csda = pd.read_csv(CSDA)
model = pd.read_csv(MODEL).drop(columns='Unnamed: 0')
mass = pd.read_csv(MASS)

In [40]:
csda

      run  subrun  event
0    8557      95   4543
1    8557     262  11576
2    8557     300  13318
3    8557     453  19810
4    8557     458  20032
..    ...     ...    ...
432  9786      31   2905
433  9787      34   3446
434  9788     135  11048
435  9788     187  16326
436  9788     243  21458

[437 rows x 3 columns]

In [41]:
model

      run  subrun  event
0    8557      44   2258
1    8557      52   2623
2    8557      71   3486
3    8557      73   3571
4    8557     150   7022
..    ...     ...    ...
797  9788     181  15670
798  9788     216  19172
799  9788     243  21458
800  9788     247  21771
801  9788     267  23425

[802 rows x 3 columns]

In [42]:
overlap = csda.merge(model, how='inner')
coverage = (len(overlap) / len(csda)) * 100
print(f"Overlap: {coverage:.2f}% ({len(overlap)} of {len(csda)} csda rows found in model)")

Overlap: 17.85% (78 of 437 csda rows found in model)